#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  7 19:07:49 2021

@author: AlvinDevasia
"""

##Connecting to API that contains COVID-19 data for U.S

import pandas as pd
import requests

jsonResponse = requests.get('https://api.covidtracking.com/v2/states.json')


jsonResponse.status_code
jsonResponse.json()




